<?php $_option = $this->getOption() ?>
<?php $_selections = $_option->getSelections() ?>
<dt><label<?php if ($_option->getRequired()) echo ' class="required"' ?>><?php echo $this->escapeHtml($_option->getTitle()) ?><?php if ($_option->getRequired()) echo '<em>*</em>' ?></label></dt>
<dd<?php if ($_option->decoratedIsLast){?> class="last"<?php }?>>
    <div class="input-box">
    <?php if (count($_selections) == 1 && $_option->getRequired()): ?>
        <?php echo $this->getSelectionQtyTitlePrice($_selections[0]) ?>
        <input type="hidden" name="bundle_option[<?php echo $_option->getId() ?>]" value="<?php echo $_selections[0]->getSelectionId() ?>"/>
    <?php else:?>
        <ul class="options-list">
        <?php foreach($_selections as $_selection): 
		$qty_stock = (int)Mage::getModel('cataloginventory/stock_item')->loadByProduct($_selection)->getQty();
		?>
            <li><input onclick="bundle.changeSelection(this)" class="bundle-checkbox change-container-classname checkbox bundle-option-<?php echo $_option->getId() ?> <?php if ($_option->getRequired()) echo 'validate-one-required-by-name' ?>" id="bundle-option-<?php echo $_option->getId() ?>-<?php echo $_selection->getSelectionId() ?>" type="checkbox" name="bundle_option[<?php echo $_option->getId() ?>][]"<?php if ($this->_isSelected($_selection)) echo ' checked="checked"' ?><?php if (!$_selection->isSaleable()) echo ' disabled="disabled"' ?> value="<?php echo $_selection->getSelectionId() ?>"/>
                <span class="label"><label for="bundle-option-<?php echo $_option->getId() ?>-<?php echo $_selection->getSelectionId() ?>"><?php echo $this->getSelectionQtyTitlePrice($_selection) ?></label></span>
                <?php if($_option->getRequired()): ?>
                    <?php echo $this->setValidationContainer('bundle-option-'.$_option->getId().'-'.$_selection->getSelectionId(), 'bundle-option-'.$_option->getId().'-container') ?>
                <?php endif; ?>
				<input type="hidden" id="minQty_<?php echo $_selection->getSelectionId(); ?>" name="minQty" value="<?php echo $_selection->getStockItem()->getMinSaleQty(); ?>"/>
				<input type="hidden" id="maxQty_<?php echo $_selection->getSelectionId(); ?>" name="maxQty" value="<?php echo $_selection->getStockItem()->getMaxSaleQty(); ?>"/>
				<input type="hidden" id="qtyStock_<?php echo $_selection->getSelectionId(); ?>" name="qtyStock" value="<?php echo $qty_stock; ?>"/>
				<input type="hidden" id="qty_default<?php echo $_selection->getSelectionId(); ?>" name="qty_default" value="<?php echo $_selection->getSelectionQty(); ?>"/>
				<input type="hidden" id="proName<?php echo $_selection->getSelectionId(); ?>" name="proName" value="<?php echo $_selection->getName(); ?>"/>
				<input type="hidden" id="item-selected-checkbox-<?php echo $_selection->getSelectionId(); ?>" class="item-selected" name="item-selected" value="<?php if ($this->_isSelected($_selection)) { echo $_selection->getSelectionId(); }?>"/>
			</li>
        <?php endforeach; ?>
        </ul>
        <div id="bundle-option-<?php echo $_option->getId() ?>-container"></div>
    <?php endif; ?>
    </div>
</dd>