<?php $_option = $this->getOption() ?>
<?php $_selections = $_option->getSelections() ?>
<dt><label<?php if ($_option->getRequired()) echo ' class="required"' ?>><?php echo $this->escapeHtml($_option->getTitle()) ?><?php if ($_option->getRequired()) echo '<em>*</em>' ?></label></dt>
<dd<?php if ($_option->decoratedIsLast){?> class="last"<?php }?>>
    <div class="input-box">
    <?php if (count($_selections) == 1 && $_option->getRequired()): ?>
        <?php echo $this->getSelectionQtyTitlePrice($_selections[0]) ?>
        <input type="hidden" name="bundle_option[<?php echo $_option->getId() ?>]" value="<?php echo $_selections[0]->getSelectionId() ?>"/>
    <?php else: ?>
        <select class="bundle-multi bundle-validate-multi" onchange="bundle.changeSelection(this)" multiple="multiple" size="5" id="bundle-option-<?php echo $_option->getId() ?>" name="bundle_option[<?php echo $_option->getId() ?>][]" class="bundle-option-<?php echo $_option->getId() ?><?php if ($_option->getRequired()) echo ' required-entry' ?> bundle-option-select multiselect change-container-classname">
        <?php if(!$_option->getRequired()): ?>
            <option value=""><?php echo $this->__('None') ?></option>
        <?php endif; ?>
        <?php foreach ($_selections as $_selection): ?>
            <option value="<?php echo $_selection->getSelectionId() ?>"<?php if ($this->_isSelected($_selection)) echo ' selected="selected"' ?><?php if (!$_selection->isSaleable()) echo ' disabled="disabled"' ?>><?php echo $this->getSelectionQtyTitlePrice($_selection, false) ?></option>
        <?php endforeach; ?>
        </select>
    <?php endif; ?>
	<?php foreach ($_selections as $_selection):
		$qty_stock = (int)Mage::getModel('cataloginventory/stock_item')->loadByProduct($_selection)->getQty();
	?>
	<input type="hidden" id="minQty_<?php echo $_selection->getSelectionId(); ?>" name="minQty" value="<?php echo $_selection->getStockItem()->getMinSaleQty(); ?>"/>
	<input type="hidden" id="maxQty_<?php echo $_selection->getSelectionId(); ?>" name="maxQty" value="<?php echo $_selection->getStockItem()->getMaxSaleQty(); ?>"/>
	<input type="hidden" id="qtyStock_<?php echo $_selection->getSelectionId(); ?>" name="qtyStock" value="<?php echo $qty_stock; ?>"/>
	<input type="hidden" id="qty_default<?php echo $_selection->getSelectionId(); ?>" name="qty_default" value="<?php echo $_selection->getSelectionQty(); ?>"/>
	<input type="hidden" id="proName<?php echo $_selection->getSelectionId(); ?>" name="proName" value="<?php echo $_selection->getName(); ?>"/>
	<input type="hidden" id="item-selected-multi<?php echo $_selection->getSelectionId(); ?>" class="item-selected" name="item-selected" value="<?php if ($this->_isSelected($_selection)) { echo $_selection->getSelectionId(); }?>"/>
	<?php endforeach; ?>
    </div>
</dd>