<?php
/*------------------------------------------------------------------------
 # Copyright (c) 2014 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/

global $var_yttheme;  
// Include cpanel
if( $var_yttheme->getParam('showCpanel') ) { ?>
<div id="cpanel_wrapper" style="direction: ltr">
	<div class="cpanel-head">
		<span>Template Settings</span>
		<div class="action cpanel-reset">
			<!--<input id="yt_button_cpanel" class="btn btn-info" type="button" onclick="javascript: onCPApply();" value="Apply" class="button" />-->
			<a class="btn btn-info reset" href="#" onclick="javascript: onCPResetDefault(TMPL_COOKIE);">Reset</a>
		</div>		
	</div>

	
	<div class="accordion" id="ytcpanel_accordion">
		<!--Theme-->
        <div class="accordion-group cpanel-theme cpanel-theme-color">
            <div class="accordion-heading">
                <a class="accordion-toggle"  data-parent="#ytcpanel_accordion">			
					Theme Color
				</a>
            </div>
        	<div id="ytitem_1" class="accordion-theme">
                <div class="accordion-inner clearfix">
					<div class="color-theme">
						<span title="Maroon" 		class="theme-color maroon<?php echo ($var_yttheme->getParam('sitestyle')=='maroon')?' active':'';?>">Maroon</span>
						<span title="Green" 		class="theme-color green<?php echo ($var_yttheme->getParam('sitestyle')=='green')?' active':'';?>">Green</span>
						<span title="Brownred" 		class="theme-color brownred<?php echo ($var_yttheme->getParam('sitestyle')=='brownred')?' active':'';?>">Brownred</span>
						<span title="Blueviolet" 	class="theme-color blueviolet<?php echo ($var_yttheme->getParam('sitestyle')=='blueviolet')?' active':'';?>">Blueviolet</span>
					</div>
				</div>
			</div>
        </div>
	
		<!--Store-->
		<div class="accordion-group cpanel-store">
			<div class="accordion-heading">
				<a class="accordion-toggle" data-parent="#ytcpanel_accordion" href="#ytitem_2">
				Layout Style</a>
			</div>
			<div id="ytitem_2" class="accordion-store">
				<div class="accordion-inner clearfix">
					<div class="cp-item">
						<div class="inner">
							<?php echo $this->getChildHtml('store_switcher');?>
						</div>
					</div>
					<!-- Select Layout -->
					<div class="cp-item layout-option">
						
						<div class="inner">
							<select onchange="javascript: onCPApply();" name="ytcpanel_layoutstyle" class="cp_select">
								<option value="1" <?php echo ($var_yttheme->getParam('layoutstyle')=='1')?' selected="selected"':'';?>>Full Width</option>
								<option value="2" <?php echo ($var_yttheme->getParam('layoutstyle')=='2')?' selected="selected"':'';?>>Boxed</option>
							</select>
						</div>
					</div>					
				</div>
			</div>
		</div>	
			

		<!-- Menu -->
		<div class="accordion-group cpanel-menu">
			<div class="accordion-heading">
				<a class="accordion-toggle" data-parent="#ytcpanel_accordion">
				Menu style </a>
			</div>
			<div id="ytitem_6" class="accordion-body">
				<div class="accordion-inner clearfix">
					<!-- Styles -->
					<div class="cp-item footer-background-color">
						<!--span>Styles</span-->
						<div class="inner">
							<select onchange="javascript: onCPApply();" name="ytcpanel_menustyle" class="cp_select">
								<option value="mega" <?php echo ($var_yttheme->getParam('menustyle')=='mega')?' selected="selected"':'';?>>Mega</option>
								<option value="css" <?php echo ($var_yttheme->getParam('menustyle')=='css')?' selected="selected"':'';?>>Css</option>
								
							</select>
						</div>
					</div>
				</div>
			</div>
		</div>

	</div>
	<div id="cpanel_btn" class="normal">
		<i class="icon-hand-left"></i>
	</div>
</div>

<script type="text/javascript">
	// <![CDATA[
    $jsmart(document).ready(function($){
		function templateSetting(array){
			if(array['0']){
				$('.body-background-color input.miniColors').attr('value', array['0']);
				$('.body-background-color a.miniColors-trigger').css('background-color', array['0']);
				$('input.ytcpanel_bgcolor').attr('value', array['0']);
			}
			if(array['1']){
				$('.link-color input.miniColors').attr('value', array['1']);
				$('.link-color a.miniColors-trigger').css('background-color', array['1']);
				$('input.ytcpanel_linkcolor').attr('value', array['1']);
			}
			if(array['2']){
				$('.text-color input.miniColors').attr('value', array['2']);
				$('.text-color a.miniColors-trigger').css('background-color', array['2']);
				$('input.ytcpanel_textcolor').attr('value', array['2']);
			}
			if(array['3']){
				$('.header-background-color input.miniColors').attr('value', array['3']);
				$('.header-background-color a.miniColors-trigger').css('background-color', array['3']);
				$('input.ytcpanel_header-bgcolor').attr('value', array['3']);
			}
			if(array['4']){
				$('.header-background-image .pattern').removeClass('active');
				$('.header-background-image .pattern.'+array['4']).addClass('active');
				$('input[name$="ytcpanel_header-bgimage"]').attr('value', array['4']);
			}
			if(array['5']){
				$('.footer-background-color input.miniColors').attr('value', array['5']);
				$('.footer-background-color a.miniColors-trigger').css('background-color', array['5']);
				$('input.ytcpanel_footer-bgcolor').attr('value', array['5']);
			}
			if(array['6']){
				$('.footer-background-image .pattern').removeClass('active');
				$('.footer-background-image .pattern.'+array['6']).addClass('active');
				$('input[name$="ytcpanel_footer-bgimage"]').attr('value', array['6']);
			}
			if(array['7']){
				$('.body-background-image .pattern').removeClass('active');
				$('.body-background-image .pattern.'+array['7']).addClass('active');
				$('input[name$="ytcpanel_body-bgimage"]').attr('value', array['7']);
			}
		}
		
		var array 				= Array('bgcolor','linkcolor','textcolor');
		var array_maroon 		= Array('#FFFFFF','#909090',  '#686868');
		var array_green			= Array('#FFFFFF','#909090',  '#686868');
		var array_brownred 		= Array('#FFFFFF','#909090',  '#686868');
		var array_blueviolet   	= Array('#FFFFFF','#909090',  '#686868');

		$('.theme-color.maroon').click(function(){
			$($(this).parent().find('.active')).removeClass('active'); $(this).addClass('active');
			createCookie(TMPL_NAME+'_'+'sitestyle', $(this).html().toLowerCase(), 365);
			templateSetting(array_maroon);
			onCPApply();
		});
		$('.theme-color.green').click(function(){
			$($(this).parent().find('.active')).removeClass('active'); $(this).addClass('active');
			createCookie(TMPL_NAME+'_'+'sitestyle', $(this).html().toLowerCase(), 365);
			templateSetting(array_green);
			onCPApply();
		});
		$('.theme-color.brownred').click(function(){
			$($(this).parent().find('.active')).removeClass('active'); $(this).addClass('active');
			createCookie(TMPL_NAME+'_'+'sitestyle', $(this).html().toLowerCase(), 365);
			templateSetting(array_brownred);
			onCPApply();
		});
		$('.theme-color.blueviolet').click(function(){
			$($(this).parent().find('.active')).removeClass('active'); $(this).addClass('active');
			createCookie(TMPL_NAME+'_'+'sitestyle', $(this).html().toLowerCase(), 365);
			templateSetting(array_blueviolet);
			onCPApply();
		});	
    });
	// ]]>
    </script>
<?php } ?>

<?php
if(!defined('ACCORDION_SNYDERPLACE')){
    define('ACCORDION_SNYDERPLACE', 1);
?>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery.cookie.min.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery.accordion_snyderplace.js') ?>"></script>
<?php } ?>

