<?php
/*------------------------------------------------------------------------
 # SM Slick Slider - Version 1.1
 # Copyright (c) 2009-2011 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.smartaddons.com
-------------------------------------------------------------------------*/
?>

<?php 
 $divid = rand().time();
 $smarthelper= Mage::helper('slickslider/utils');
 $items = $this->getProducts();
 $config = $this->getConfigObject();
 $readmore = Mage::helper('slickslider')->__('read more...');
?>
<?php if(count($items)>0):?>
	<?php echo $this->getScriptTags(); ?>
<script type="text/javascript">
//<![CDATA[

$jsmart(document).ready(function($) {
	function init(){
		$('#featured<?php echo $divid;?>').cycleYtc({
			fx:     '<?php echo $config['animation'];?>',
			timeout: <?php echo $config['interval'];?>,
			speed:  <?php echo $config['duration'];?>, 
			next:   '#next<?php echo $divid;?>', 
			prev:   '#prev<?php echo $divid;?>',
			pause: <?php echo ($config['autoplay'])?1:0;?>,
			divId: '<?php echo $divid;?>',
			readmoreImg:'<?php echo $readmore;?>',
			theme:'<?php echo $config['theme'];?>',
			linktarget:'<?php echo $config['product_links_target'];?>',
			linkcaption:<?php echo $config['product_title_linkable'];?>,
			autoPlay: <?php echo $config['autoplay'];?>,
			startingSlide:<?php echo ($config['start_item'])?$config['start_item']:0;?>,
			
			after: function(current,next){	
			},
			debug: true
		});		
		if($('#featured<?php echo $divid;?>').height()<=50){
			return false;	
		}

		$('#current_content_<?php echo $divid;?>').show();
		<?php if($config['prenext_show']){	?>
			$('#cover_buttons_<?php echo $divid;?>').show();
		<?php } ?>
		return true;
	}
	e = $(".ytc_background_theme1"),ehtml=e.html(),id='';
	
	function forceShow(){		
		e.children().empty().remove();e.html(ehtml);if(!init()){			
		setTimeout(	function(){	forceShow();},400);
		}
	}
	forceShow();
  	
});

//]]>
</script>

	<?php ob_start();?>
	<div class="ytc-content-slickslider" style=" <?php if(!$config['show_img_on_right']){?>float:left;<?php }?> ">
		<div class="<?php /* visible-phone */ ?> wrapper-paging">
			<div id="featured<?php echo $divid;?>" style="position:relative; max-width:100%;overflow:hidden;z-index:1;" >
				<?php 
					$i = 1;
					foreach($items as $key=>$item) {	?>
						<?php $removeHttp =	str_replace('http://','', $item['link']); ?>
						<a style="max-width:100%;<?php if(!$i){	?>display:none;<?php }  ?>" href="<?php echo ($config['product_image_linkable'])?$item['link']:"#";?>" <?php echo $smarthelper->getTargetAttr($config['product_links_target']); ?> >
							<img src="<?php echo $item['thumb']?>" alt="<?php echo $item['title']?>"   style=""/>
						</a>
				<?php	$i = 0; } ?> 
			</div>		
					
			<div class="paging-next-prev">
				<a id="prev<?php echo $divid;?>" data-slide="prev" href="javascript:void(0)" class="left carousel-control" style="font-family:Helvetica Neue,Helvetica,Arial,sans-serif;"></a>					
				<a id="next<?php echo $divid;?>" data-slide="next" href="javascript:void(0)" class="right carousel-control" style="font-family:Helvetica Neue,Helvetica,Arial,sans-serif;"></a>				
			</div>		
		</div>		
		<div class="paging-btn <?php echo $config['theme'];?>" id="cover_buttons_<?php echo $divid;?>" style="width: auto; position:absolute; display:none;">
			<div class="hidden-phone">	
			<div style="width:100%;" class="buttons_<?php echo $config['theme'];?> yt_button">					
				<ul id="image_button_<?php echo $divid;?>" <?php if($config['button_theme']=='cycle'){?> class="cycle"<?php }?>>
					<?php foreach($items as $key=>$item) {?>
						<?php if($config['button_theme']=='number'){?>
						<li class="<?php echo ($key==$config['start_item'])?"button_img_selected":"button_img";?>"  value="<?php echo $key;?>"><p>0<?php echo ($key+1);?></p><?php /* <span class="inner-border"></span> */ ?></li>
						<?php }else{?>
							<li class="<?php echo ($key==$config['start_item'])?"button_img_selected":"button_img";?>" value="<?php echo $key;?>"></li>
						<?php }?>
					<?php } ?> 
				</ul>
			</div>	
		</div>				
		</div>			
	</div>
<?php $slide_image = ob_get_contents(); ob_end_clean();?>
<?php ob_start();?>

	<div class="ytc-content-box" id="content_box_<?php echo $divid;?>" style="<?php /* width:<?php echo $config['desc_box_width'];?>px; height:<?php echo ($config['product_image_height'])?>px; */ ?>" >	
		<div class="content-box">			
				<div class="block-content" id="current_content_<?php echo $divid;?>" style="display:<?php echo ($config['product_description_disp'])?'block':'none'?>;"></div>				
		</div>	
	</div>

<?php $slide_desc = ob_get_contents(); ob_end_clean();?>
	
<div class="ytc-content ytc_background_<?php echo $config['theme'];?> lifted">
<?php
	if($config['show_img_on_right'])
	{
		$config['readmore_left'] = 137;
		echo $slide_desc.$slide_image;
	}
	else
	{
		$config['readmore_left'] = ($config['product_image_width'] + $config['desc_box_width']) - 284;
		echo $slide_image.$slide_desc;
	}
?>
	<div id="read_more_content_<?php echo $divid;?>" class="readmore_button" style="bottom:20px; left:<?php echo $config['readmore_left']?>px; width:144px; position: absolute; z-index:100;display:<?php echo ($config['product_details_page_link_disp'])?'block':'none'?>"></div>
	<?php /*<div class="footer-bg"></div> */ ?>
</div>

<div style="display:none">
<?php foreach($items as $key=>$item) {?>
	<div id="arrContent_<?php echo $divid;?>_<?php echo $key;?>">
<?php	if($config['product_title_disp']){	?>
			<div class="block-title">
				<div class="inner-title">
					<a href="<?php echo ($config['product_image_linkable'])?$item['link']:"#";?>" <?php echo $smarthelper->getTargetAttr($config['product_links_target']); ?> onclick="<?php if($config['product_image_linkable']):?>javascript: return true; <?php else: ?>javascript: return false; <?php endif;?>">
						<?php echo $item['title']?>
					</a>		
				</div>	
			</div>
<?php  	}	?>
<?php 	
		$_product = Mage::getModel('catalog/product')->load($item['id']);

		if($config['product_price_disp'] AND $item['price']!=''){	
			echo $this->getPriceHtml($_product);		
		}	
?>	
<?php	if($config['product_description_disp']){	?>
			<div class="block-description">
				<div class="inner-desc">
					<span class="sub-content"><?php echo $item['sub_content']?></span>
				</div>
			</div>
<?php  	}	?>			
<?php 	if($_product->isSaleable()){ ?>
			<a title="<?php echo $this->__('Add to Cart') ?>" href="javascript:void(0);" class="btn-cart bgcolor fontcolor" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span <?php /* class="icon-plus" */ ?>><?php echo $this->__('Add to Cart') ?></span></span></a>
<?php 	}else{ ?>
			<span class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></span>
<?php 	} ?>			
	</div>
<?php } ?> 
</div>
<?php else: ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php endif;?>
<?php if(!empty($config['posttext'])):?>
<div style="text-align:left">
	<p><?php  echo $config['posttext'];?></p>
</div>
<?php endif;?>